### PR TITLE
Updated content

### PR DESCRIPTION
**Pull request by adamjonas**

### CODE REVIEW

File: README.md [hunk 1]
```diff
@@ -1,53 +1,144 @@
...
+By using ActiveRecord you are also able to perform advanced query tasks, such as method chaining and scoping, which typically requires less code and makes for a more readable query.
 
-Our database might have a first_name and last_name column, which AR provides access to with first_name, and last_name readers/writers, but if we wanted to print a full_name, we'd build a full_name instance method that combines the first_name and last_name, so our models aren't just data, but also we build these sort of data helper methods.
+## ActiveRecord Models
 
-First we need a table, so let's make a migration (they've done this before!)
+So if we have a database table, why do we need a model file? By using model files we are able to create an organized layer of abstraction for our data. An important item to remember is that at the end of the day the model file is a Ruby class. It will typically inherit from the ActiveRecord::Base class, which means that it has access to a number of methods that assist in working with the database. However, you can treat it like a regular Ruby class, allowing you to create methods, data attributes, and everything else that you would want to do in a class file.
```
Comment (adamjonas) [inline README.md]: `ActiveRecord::Base` should probably have backticks.

File: README.md [hunk 2]
```diff
@@ -1,53 +1,144 @@
...
 
-001_create_posts.rb
+A typical model file will contain code such as, but not limited to the following:
 
-we dont need to go too much into Migration syntax as they mostly learned this already or this readme can assume they are familiar with AR Basics such as migrations and stuff. but we'll have the migration code and link to migration docs for more information.
+* Custom scopes
```
Comment (adamjonas) [inline README.md]: Not sure that students will be familiar with all of these terms by this point. Maybe we could at least have links to external resources?

File: README.md [hunk 3]
```diff
@@ -1,53 +1,144 @@
...
+If we run ```bundle exec rspec``` it will throw an error since we don't have any code in the application for our ```post``` model yet. To fix this create a new file in the ```app/models``` directory called ```post.rb``` and add the following code:
 
-explain models are separate from controllers and views - we connect a model to a controller and a view by loading the model in a controller action, no convention there...
+```ruby
+class Post
+end
+```
 
-database.yml defines are database connection and ActiveRecord::Base.connection holds those connections.
+This will get the tests passing, but it still has some weird errors, and this is because we need to create a schema file. You can do that by running ```rake db:migrate```, this will create the schema file and clear the warning. Now update the Post spec to test for a Post being created, it will look something like this:
```
Comment (adamjonas) [inline README.md]: Something about running `rake db:migrate` feels a little weird here. Would `rake db:create` or `db:setup` not be needed? Running migrate without any migrations creates a little confusion in my head at least.

File: README.md [hunk 4]
```diff
@@ -1,53 +1,144 @@
...
+
+Also, if you are coming from other programming languages, you may be wondering how exactly we are able to connect to the database automatically, without having to create connection strings. The reason for this simplicity resides in the ```config/database.yml``` file that was generated when we created our application and ran ```rake db:create```, in that file you will see that the development, test, and production databases are all configured. From that stage the ActiveRecord::Base.connection method connects your application to the database, which is another benefit from having our model classes inherit from the ActiveRecord::Base module.
+
+Being able to work in different environments is one of the strong points of Rails, and the database.yml file takes advantage of this feature by having different database options for each type of environment. If you analyze the file you can see that you can establish different database adapters, pools, timeout values, etc. for each environment specifically. This allows for you to have a setup such as using sqlite locally and Postgres in production, along with having a segmented database environment for your testing suite.
```
Comment (adamjonas) [inline README.md]: pools, timeout values, adapters -- useful info but may overwhelm beginnings who don't know what any of those terms mean.

File: README.md [hunk 5]
```diff
@@ -1,53 +1,144 @@
...
+
+After running ```rake db:migrate``` we can see that our ```db/schema.rb``` file has been updated with our new posts table, however if we run our tests again you can see that the tests are still failing due to the error: ```undefined method `create!' for Post:Class```. This is because we left out one very important piece of code from the Post model file, in order to leverage built in methods such as ```create!``` we need to have the Post class inherit from ```ActiveRecord::Base```. Update the post.rb model file to match this below:
+
+```ruby
+class Post < ActiveRecord::Base
+end
+```
+
+Now all of the tests are passing and we can create a new post correctly. Even though we know this is working because our tests are passing, let's still test this in the console, open up the Rails console by running: ```rails c```. Once the session has started, run the following command to ensure it recognizes our new Post model:
```
Comment (adamjonas) [inline README.md]: `rails console` rather than `rails c` since they may not have used console before. Also might explain more about what's going on with it.

File: README.md [hunk 6]
```diff
@@ -1,53 +1,144 @@
...
+end
+```
+Now if you run the tests, all of them are passing and our Post model has an instance method that returns a post summary. You can test this out in the Rails console as well by running a query on the record we created, such as:
+
+```
+Post.last.post_summary
+```
+And it will return the summary value of that specfic post.
+
+As you may have noticed, we did not have to create a controller, route, view, etc. in order to get the Post model working. The data aspect of the application can work separately from the view and data flow logic, this level of abstraction makes it straightforward to test data behavior without having it strongly coupled to how it is rendered to the user. With that being said, it is considered a best practice to have your controller and view files follow the proper naming convention so that the MVC associations are straightforward to follow. For example, to build out the controller and view code for our Post model we would create the following structure:
```
Comment (adamjonas) [inline README.md]: avoid straightforward as it may not be all that straightforward for beginners

File: README.md [hunk 7]
```diff
@@ -1,53 +1,144 @@
...
+This will get the tests passing, but it still has some weird errors, and this is because we need to create a schema file. You can do that by running ```rake db:migrate```, this will create the schema file and clear the warning. Now update the Post spec to test for a Post being created, it will look something like this:
 
-That's it for models in rails for now.
+```ruby
+describe Post do
+  it 'can be created' do
+    post = Post.create!(title: "My title", description: "The post description")
+    expect(post).to be_valid
+  end
+end
```
Comment (adamjonas) [inline README.md]: It's the first time they are seeing all of this rails stuff. Shy away from also adding in writing tests. While our students are very good at reading tests, they aren't great at writing them by this time in the curriculum. We make sure they understand the content first, then a few units later after this we'll do a ton of TDD stuff. So let's just show them testing things out in `rails c` for right now

File: README.md [hunk 8]
```diff
@@ -1,53 +1,144 @@
...
+
+* Create a ```posts_controller.rb``` file that calls on the Post model
+* Create a ```views/posts/``` directory that stores the views related to the Post model
+
+Also, if you are coming from other programming languages, you may be wondering how exactly we are able to connect to the database automatically, without having to create connection strings. The reason for this simplicity resides in the ```config/database.yml``` file that was generated when we created our application and ran ```rake db:create```, in that file you will see that the development, test, and production databases are all configured. From that stage the ActiveRecord::Base.connection method connects your application to the database, which is another benefit from having our model classes inherit from the ActiveRecord::Base module.
```
Comment (adamjonas) [inline README.md]: This is valuable stuff, but a bit too much and out of context for this reading. Rails environment stuff is important, but we are saving it for later units

File: README.md (hunk 2 above)
Comment (jordanhudgens) [inline README.md]: Sounds good, I'll put links for each item to the documentation and also add a disclaimer so they aren't discouraged about not hearing about the topics yet.

**Comment by jordanhudgens** [comment]
@AnnJohn I've implemented the metadata, integrated the content changes, I kept the TDD in but I added a disclaimer for them to focus on the implementation code, let me know if that works. I really like using TDD for this since it shows them each of the possible errors they could run into and how to fix them, so it's explicit, but if it's too much let me know and I'll redo it and only show implementation.

File: README.md [hunk 9]
```diff
@@ -1,53 +1,151 @@
...
+
+Being able to work in different environments is one of the strong points of Rails, and the database.yml file takes advantage of this feature by having different database options for each type of environment. If you analyze the file you can see that you can establish different database adapters, pools, timeout values, etc. for each environment specifically. This allows for you to have a setup such as using sqlite locally and Postgres in production, along with having a segmented database environment for your testing suite. Some of these items are components that you won't need until you get into more advanced applications, however it's good to know where these items are located in the file system for when you get to that point.
```
Comment (jmburges) [inline README.md]: I would mention that "this file includes a lot of stuff you will rarely have to handle, but just remember that if anything requires database configuration it will be here"

Comment (jmburges) [inline README.md]: Also no need to fix it, but instead of the word "analyze" I would say "take a look at" Much less formal

**Comment by jmburges** [comment]
This looks good. A few things I noticed. You should explain to them that they need to run `rails new my-blog` to get things going. Or include it, but I think it's fine to not include it in this case. They are still figuring out rails. Added a comment, go ahead and fix that and just merge it. No need to pass it back to me!

:shipit:
